### ISSUE TITLE
User can view all possible friends.

### ISSUE THREAD

**Issue by ghost** [dskoglund/facebook#4]

**Comment by dskoglund** [comment]
![deef5ef8-7108-11e6-8df7-f0be6622ebf8](https://cloud.githubusercontent.com/assets/21043184/18254678/0e89e072-7355-11e6-9002-fe63b656b823.png)

**Comment by dskoglund** [comment]
![image](https://cloud.githubusercontent.com/assets/21043184/18256195/e320689a-7366-11e6-8f69-4ed4d3400171.png)
