### ISSUE TITLE
User can view current list of friends.

### ISSUE THREAD

**Issue by ghost** [dskoglund/facebook#5]

**Comment by dskoglund** [comment]
![image](https://cloud.githubusercontent.com/assets/21043184/18256210/0b8c25f8-7367-11e6-946a-0aecfe6b7e97.png)

**Comment by dskoglund** [comment]
![image](https://cloud.githubusercontent.com/assets/21043184/18256702/c061b726-736d-11e6-8a3f-0b64c76ac0cc.png)
